users:
  - username
  - username
debug: false
development: false
key: auth-key
command-prefix: $
SpideyBot:
  branch: branch-name
  color: test-result-color
  channel: 'channel'
db-connection:
  driver: 'mysql'
  username: dbuser
  password: dbpassword
  port: dbport
  host: pdhost
  database: dbname
