# Discord bot settings
discord:
  token: 'NTUxODc0MzQyODA0MjU4ODY3.D3QyNw.bHwKEE6LlhWUD7cLBVsZm-OgWSQ'             # Get bot token at https://discordapp.com/developers/
  channel: '552711633269686292'           # Discord channel for information messages
  command-prefix: '~'
  admin-users:
    - 'DenisGeek'                # nickname from discord

# Optional. Settings for commands
db-settings:
  driver: 'mysql'       # Database driver (mysql, psql, etc.)
  username: 'admin'          # Database username
  password: 'ZAQ!2wsx'          # Database user password
  port: 3306            # Database port (Default: 3306)
  host: 'localhost'     # Database host (Default: localhost)
  database: 'Soer.Bot'          # Database name

# Switch on debug mode (true/false)
debug: false

# Switch on development mode (true/false)
development: false

# Optional. Settings for travis-ci web-hooks
SpideyBot:
  branch: 'develop'            # Branch name for inspection
  color: 'green'             # Color for test: green


